--- # Creating a partition
- hosts: all
  user: ansible
  connection: ssh
  pre_tasks:
  - name: When did the ROLE start
    raw: date > /home/ansible/startofrole.log
  roles:
    - install
    - adduser
    - updating
  post_tasks:
  - name: When did the ROLE end
    raw: date > /home/ansible/endofrole.log
