--- # Creating a partition
- hosts: all
  vars:
    lvm_apply: true
    lvm_groups:
      - vgname: vg_data
        disks: /dev/sdb3
        create: true
        lvnames:
        - lvname: vg_data_bka
          size: 1g
          create: true
          filesystem: xfs
          mount: yes
          mount_point: /bka
          mount_options: 'defaults,noatime'
        - lvname: vg_data_paa
          size: 1g
          create: true
          filesystem: xfs
          mount: true
          mount_point: /paa
          mount_options: 'defaults,noatime'
  user: ansible
  connection: ssh
  pre_tasks:
  - name: When did the ROLE start
    raw: date > /home/ansible/startofrole.log
  roles:
    - mount
    - lvm
  post_tasks:
  - name: When did the ROLE end
    raw: date > /home/ansible/endofrole.log
